import type { Traveler } from "@/lib/travelers/types";

/**
 * Mock traveler data shared by the map and discovery features.
 * Phase 3/4 placeholder — replaced by a Supabase realtime feed later.
 */
export const mockTravelers: Traveler[] = [
  {
    id: "t1",
    username: "alexrivera",
    displayName: "Alex Rivera",
    status: "exploring",
    initials: "AR",
    place: "Lisbon, Portugal",
    interests: ["surf", "coffee", "photography"],
    coords: [-9.1393, 38.7223],
  },
  {
    id: "t2",
    username: "mei_w",
    displayName: "Mei Wong",
    status: "local",
    initials: "MW",
    place: "Bangkok, Thailand",
    interests: ["food", "nightlife", "markets"],
    coords: [100.5018, 13.7563],
  },
  {
    id: "t3",
    username: "jonask",
    displayName: "Jonas Keller",
    status: "transit",
    initials: "JK",
    place: "Berlin, Germany",
    interests: ["techno", "art", "cycling"],
    coords: [13.405, 52.52],
  },
  {
    id: "t4",
    username: "sofia.m",
    displayName: "Sofia Marino",
    status: "exploring",
    initials: "SM",
    place: "Mexico City, Mexico",
    interests: ["food", "history", "hiking"],
    coords: [-99.1332, 19.4326],
  },
  {
    id: "t5",
    username: "amarak",
    displayName: "Amara Koffi",
    status: "exploring",
    initials: "AK",
    place: "Cape Town, South Africa",
    interests: ["hiking", "wine", "photography"],
    coords: [18.4241, -33.9249],
  },
  {
    id: "t6",
    username: "liamoc",
    displayName: "Liam O'Connor",
    status: "local",
    initials: "LO",
    place: "Sydney, Australia",
    interests: ["surf", "coffee", "diving"],
    coords: [151.2093, -33.8688],
  },
  {
    id: "t7",
    username: "priyas",
    displayName: "Priya Sharma",
    status: "transit",
    initials: "PS",
    place: "Mumbai, India",
    interests: ["food", "music", "markets"],
    coords: [72.8777, 19.076],
  },
  {
    id: "t8",
    username: "noah_b",
    displayName: "Noah Brooks",
    status: "exploring",
    initials: "NB",
    place: "New York, USA",
    interests: ["art", "nightlife", "running"],
    coords: [-74.006, 40.7128],
  },
  {
    id: "t9",
    username: "elenap",
    displayName: "Elena Petrova",
    status: "exploring",
    initials: "EP",
    place: "Rio de Janeiro, Brazil",
    interests: ["beach", "dancing", "hiking"],
    coords: [-43.1729, -22.9068],
  },
  {
    id: "t10",
    username: "kenji_t",
    displayName: "Kenji Tanaka",
    status: "local",
    initials: "KT",
    place: "Tokyo, Japan",
    interests: ["food", "photography", "gaming"],
    coords: [139.6917, 35.6895],
  },
];
